name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: hashicorp/setup-terraform@v2
    - name: Install Terraform Docs
      run: |
        wget -O terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
        tar xzf terraform-docs.tar.gz
        sudo mv terraform-docs /usr/local/bin/
        terraform-docs --version
    - name: Install TFlint
      run: |
        wget -O tflint.tar.gz https://github.com/terraform-linters/tflint/releases/download/v0.47.0/tflint_linux_amd64.zip
        unzip tflint.tar.gz
        sudo mv tflint /usr/local/bin/
        tflint --version
    - uses: pre-commit/action@v3.0.0
